<?php

namespace TplmBundle\Repository;

/**
 * User_accountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_accountRepository extends \Doctrine\ORM\EntityRepository
{
}
