<?php

namespace Proxies\__CG__\TplmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \TplmBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'label', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'maxAnswer', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'hasOrder', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'isMultiSelect', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'choices'];
        }

        return ['__isInitialized__', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'id', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'label', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'maxAnswer', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'hasOrder', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'isMultiSelect', '' . "\0" . 'TplmBundle\\Entity\\Question' . "\0" . 'choices'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxAnswer($maxAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxAnswer', [$maxAnswer]);

        return parent::setMaxAnswer($maxAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxAnswer', []);

        return parent::getMaxAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasOrder($hasOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasOrder', [$hasOrder]);

        return parent::setHasOrder($hasOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasOrder', []);

        return parent::getHasOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMultiSelect($isMultiSelect)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMultiSelect', [$isMultiSelect]);

        return parent::setIsMultiSelect($isMultiSelect);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMultiSelect()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMultiSelect', []);

        return parent::getIsMultiSelect();
    }

    /**
     * {@inheritDoc}
     */
    public function addChoice(\TplmBundle\Entity\Choice $choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChoice', [$choice]);

        return parent::addChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChoice(\TplmBundle\Entity\Choice $choice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChoice', [$choice]);

        return parent::removeChoice($choice);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoices', []);

        return parent::getChoices();
    }

}
